### PR TITLE
ongoing work to transform current test into class

### PR DESCRIPTION
**Pull request by lfunderburk**
Will be adding work on an ongoing bases
First attempt at refactoring repertoire check test into class

### CODE REVIEW

**Comment by lfunderburk** [comment]
@bcorrie  this needs to be tested on the turnkey
tested on cedar

**Comment by lfunderburk** [comment]
script name and parameters are exactly the same as before
docker file and other files sanity check is used on can be kept the same

**Comment by bcorrie** [comment]
Made some minor changes to the sanity check output, fixed a bug - merging.

**Review by bcorrie — APPROVED** [review]
Approved...

**Pull request merged**
